meddo/meddo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meddoapp/',include('meddoapp.urls'))
]

meddo/meddoapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import HomeView, TripCreateView, TripDetailView, TripListView, SignUpView

app_name = 'meddoapp'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('create_trip',TripCreateView.as_view(),name='create_trip'),
    path('detail_trip/<int:pk>/',TripDetailView.as_view(),name='detail_trip'),
    path('list_trip',TripListView.as_view(),name='list_trip'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='meddoapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

meddo/meddoapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, User


# Create your models here.
# # Custom User Manager
# class UserManager(BaseUserManager):
#     def create_user(self, username, password=None):
#         if not username:
#             raise ValueError("Users must have a username")
#         user = self.model(username=username)
#         user.set_password(password)
#         user.save(using=self._db)
#         return user

#     def create_superuser(self, username, password):
#         user = self.create_user(
#             username=username,
#             password=password,
#         )
#         user.is_admin = True
#         user.save(using=self._db)
#         return user

# # User Model
# class User(AbstractBaseUser):
#     username = models.CharField(max_length=255, unique=True)
#     password = models.CharField(max_length=255)

#     objects = UserManager()

#     USERNAME_FIELD = 'username'
#     REQUIRED_FIELDS = []  # Passwords are required by default

#     def __str__(self):
#         return self.username

# Trip Model
class Trip(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    trip_name = models.CharField(max_length=255)
    #location = models.CharField(max_length=255)
    start_date_time = models.DateTimeField()
    end_date_time = models.DateTimeField()
    #transportation = models.CharField(max_length=255)

    def __str__(self):
        return self.trip_name

# Place Model
class Place(models.Model):
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    place_name = models.CharField(max_length=255)

    def __str__(self):
        return self.place_name
    
class Plan(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    start_date_time = models.DateTimeField()
    end_date_time = models.DateTimeField()

    def __str__(self):
        return self.place.place_name
    

meddo/meddoapp/forms.py
from django import forms
from .models import Trip, Place
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['start_date_time', 'end_date_time', 'trip_name']
        widgets = {
            'start_date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            # Add other customizations here
        }

class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ['place_name']

class SignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

meddo/meddoapp/views.py
from django.shortcuts import render
from django.urls import reverse,reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView,ListView,DetailView, UpdateView, DeleteView
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from meddoapp.models import Trip, Place, User
from .forms import TripForm, PlaceForm, SignUpForm
from django.conf import settings

def map_view(request):
    context = {
        'google_maps_api_key': settings.GOOGLE_MAPS_API_KEY
    }
    return render(request, 'your_template.html', context)


# Create your views here.

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "meddoapp/home.html"


class TripCreateView(LoginRequiredMixin, CreateView):
    model = Trip
    form_class = TripForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('meddoapp:detail_trip', kwargs={'pk': self.object.pk})


class TripListView(LoginRequiredMixin, ListView):
    model = Trip
    queryset = Trip.objects.order_by("start_date_time")
    context_object_name = "trip_list"

    def get_queryset(self):
        return Trip.objects.filter(user=self.request.user)




class TripDetailView(LoginRequiredMixin, DetailView, FormView):
    model = Trip
    context_object_name = "trip"
    form_class = PlaceForm
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['google_maps_api_key'] = settings.GOOGLE_MAPS_API_KEY
        return context

    def get_object(self):
        obj = super().get_object()
        if obj.user != self.request.user:
            return HttpResponseForbidden("You are not allowed to view this page.")
        return obj


class PlaceCreateView(LoginRequiredMixin, CreateView):
    model = Place



class SignUpView(FormView):
    template_name = 'meddoapp/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

meddo/meddoapp/templates/meddoapp/home.html
{% extends "base.html" %}

{% block title %}MeddoMap | Home {% endblock title %}

{% block content %}
{% load static %}

    <style>
        body::before {
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-image: url("{% static 'images/bg2.jpeg' %}");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            opacity: 0.7; /* Adjust the opacity level here */
            z-index: -1;
            
        }

        .plan-new{
            right: 35%;
            position: absolute;
            align-items: right;
        }

    </style>


    <!-- Body Content -->
    <div class="content-container">
        <div class="container">
            <h1>Welcome to Meddo Map!</h1>
                 <div class="plan-new">

                  <h2 class="">Where are you going next?</h2>
                  <div class="new-trip-button">
                    <a href= "{% url 'meddoapp:create_trip' %}"><button class="btn btn-warning" type="button">Plan a New Trip</button></a>
                  </div>
                </div>
            
        </div>
    </div>

{% endblock content %}


{% block scripts %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBqOCodGn-7Cgc7gJxnLinHNsAZruE0WfA&libraries=places&callback=initMap" async defer></script>
{% endblock scripts %}

meddo/meddoapp/templates/meddoapp/login.html
<!-- templates/login.html -->
{% extends "base.html" %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <p>Don't have an account? <a href="{% url 'meddoapp:signup' %}">Sign up here</a></p>
{% endblock %}

meddo/meddoapp/templates/meddoapp/signup.html
<!-- templates/signup.html -->
{% extends "base.html" %}

{% block content %}
  <h2>Sign Up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
  <p>Already have an account? <a href="{% url 'meddoapp:login' %}">Login here</a></p>
{% endblock %}

meddo/meddoapp/templates/meddoapp/trip_detail.html
{% extends "base.html" %}
{% load static %}


{% block title %}MeddoMap | {{ trip }} {% endblock title %}

{% block content %}
<style>
    .map {
        height: 600px;
        width: 68%;
    }
    .right {
        position:fixed;
        top: 100px;
        left: 30%;

    }

    .left {
        width: 50%;
        margin-top: 20px;
    }

    .create-btn {
        position: fixed;
        top: 120px;
        right: 5%;
    }

    .card {
        margin-top: 10px !important;
        width: 18rem;
    }

    
</style>
<div class="content-container">
    <div class="container">
        <div class="row">
        <div class="left">
        <div class="col">
            <h2>Places</h2>
            <div class="places">
                <div id="place-list"></div>
            </div>
            <div class="info">
                <div id="place-info"></div>
            </div> 
        </div>
    </div>
        <div class="right">
        <div class="col">
            <h2>{{ trip }}</h2>
            <div class="create-btn">
            <a href="#" class="btn btn-warning create-plan">Create a Plan</a>
            </div>
            <div class="map" id="map"></div>   
        </div>
    </div>
    </div>
             
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script src="{% static 'js/app.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&libraries=places&callback=initMap" async defer></script>
{% endblock scripts %}

meddo/meddoapp/templates/meddoapp/trip_form.html
{% extends "base.html" %}

{% block title %}MeddoMap | Home {% endblock title %}

{% block content %}
{% load static %}
<style>
    body {
        background-color: blue;

    }
    body::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: url("{% static 'images/bg2.jpeg' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
        opacity: 0.5; /* Adjust the opacity level here */
        z-index: -1;
        
    }

    .content-container {
       color: white;
    }
</style>

    <!-- Body Content -->
    <div class="content-container">
        <div class="container">
        <h1>New Trip</h1>
        {% load widget_tweaks %}

        <form method="post" class="form">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field|add_class:"form-control" }}
                {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </div>
    </div>

{% endblock content %}

meddo/meddoapp/templates/meddoapp/trip_list.html
{% extends "base.html" %}

{% block title %}Trips{% endblock title %}

{% block content %}

    <!-- Body Content -->
    <div class="content-container">
        <div class="container">
            <h1>Trips</h1>
            <ul>
                {% for trip in trip_list %}
                <li>
                    <a href="/meddoapp/detail_trip/{{trip.id}}">{{trip.trip_name}}</a>
                </li>
                {% endfor %}               
            </ul>

            
        </div>
    </div>

{% endblock content %}

meddo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}MeddoMap{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Google Fonts Link for Montserrat -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap" rel="stylesheet">
    <style>
        /* Apply the Montserrat font to the whole page */
        body {
            font-family: 'Montserrat', sans-serif;
            {% comment %} background-color: black; {% endcomment %}
            margin-top: 100px;
            margin-bottom: 60px;

        }
        .content-container{
            margin-top: 50px;
            margin-bottom: 50px;
            margin-left: 30px;
            fixed: 100%;
            align-items: center;
            justify-content: center;
            width: 1200px;
            flex: 1; 
        }
        /* Custom CSS for components */
        .main-container {
            margin-top: 20px;
            margin-left: 20px;
            margin-right: 20px;
        }
        .container, .container-fluid {
            padding-left: 0;
            padding-right: 0;
            max-width: 100%;
        }
        .navbar {
            background-color: black !important;
            font-color: black;
            position: fixed;
            top: 0;
            width: 100%;
            height: 100px;
            z-index: 1000;
        }
        .footer {
            background-color: black !important;
            font-color: white;
            position: fixed;
            bottom: 0;
            width: 100%;
            height: 60px;
            z-index: 1;
        }
        .img {
            margin-left: 30px;
            margin-right: 30px;
        }



        .content-container h1{
            font-size: 60px;
            font-weight: 700;
        }

        .content-container h2{
            font-size: 30px;
            font-weight: 600;
            margin-top: 20px;
            margin-bottom: 20px;
        }
        
    </style>
    
</head>
<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'meddoapp:home' %}">
                {% load static %}
                <img class="img" src="{% static 'images/MeddoMap3.png' %}" alt="Logo" style="height: 60px;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'meddoapp:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'meddoapp:list_trip' %}">Your Trips</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-brand">
                <button class="btn btn-info">Logout</button>
                <button class="btn btn-info">Account</button>
            </div>
        </div>
    </nav>
</header>
    <body>
        <div class = "main-container">
        {% block content %}
        {% endblock content %}
        </div>
    </body>
    
    <!-- Footer -->
    <footer class="footer bg-light text-light py-3">
        <div class="container text-center">
            <p>Copyright © Koshiro Sugioka</p>
        </div>
    </footer>

    {% block scripts %}
    {% endblock scripts %}

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</html>